// Generated by gencpp from file tuw_vehicle_msgs/RWDKinCmd.msg
// DO NOT EDIT!


#ifndef TUW_VEHICLE_MSGS_MESSAGE_RWDKINCMD_H
#define TUW_VEHICLE_MSGS_MESSAGE_RWDKINCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tuw_vehicle_msgs
{
template <class ContainerAllocator>
struct RWDKinCmd_
{
  typedef RWDKinCmd_<ContainerAllocator> Type;

  RWDKinCmd_()
    : header()
    , vel(0.0)
    , front_center_wheel_angle(0.0)
    , brake_pressure(0.0)  {
    }
  RWDKinCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vel(0.0)
    , front_center_wheel_angle(0.0)
    , brake_pressure(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _vel_type;
  _vel_type vel;

   typedef double _front_center_wheel_angle_type;
  _front_center_wheel_angle_type front_center_wheel_angle;

   typedef double _brake_pressure_type;
  _brake_pressure_type brake_pressure;





  typedef boost::shared_ptr< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> const> ConstPtr;

}; // struct RWDKinCmd_

typedef ::tuw_vehicle_msgs::RWDKinCmd_<std::allocator<void> > RWDKinCmd;

typedef boost::shared_ptr< ::tuw_vehicle_msgs::RWDKinCmd > RWDKinCmdPtr;
typedef boost::shared_ptr< ::tuw_vehicle_msgs::RWDKinCmd const> RWDKinCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator1> & lhs, const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vel == rhs.vel &&
    lhs.front_center_wheel_angle == rhs.front_center_wheel_angle &&
    lhs.brake_pressure == rhs.brake_pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator1> & lhs, const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuw_vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9dacac9c5016e81b75002abe61b3ee0";
  }

  static const char* value(const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9dacac9c5016e81ULL;
  static const uint64_t static_value2 = 0xb75002abe61b3ee0ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuw_vehicle_msgs/RWDKinCmd";
  }

  static const char* value(const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# requested speed on the center of the rear axis [m/s]\n"
"float64 vel\n"
"\n"
"# requested steering angle of the imaginary wheel at the center of the front axis [degrees]\n"
"float64 front_center_wheel_angle\n"
"\n"
"# requested brake pressure for the system in bar measured at the front brake circuit\n"
"# if > 0, vel is being overriden and 0-torque is applied on the motors\n"
"float64 brake_pressure\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vel);
      stream.next(m.front_center_wheel_angle);
      stream.next(m.brake_pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RWDKinCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuw_vehicle_msgs::RWDKinCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    s << indent << "front_center_wheel_angle: ";
    Printer<double>::stream(s, indent + "  ", v.front_center_wheel_angle);
    s << indent << "brake_pressure: ";
    Printer<double>::stream(s, indent + "  ", v.brake_pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUW_VEHICLE_MSGS_MESSAGE_RWDKINCMD_H
