// Generated by gencpp from file tuw_vehicle_msgs/TrackMarking.msg
// DO NOT EDIT!


#ifndef TUW_VEHICLE_MSGS_MESSAGE_TRACKMARKING_H
#define TUW_VEHICLE_MSGS_MESSAGE_TRACKMARKING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace tuw_vehicle_msgs
{
template <class ContainerAllocator>
struct TrackMarking_
{
  typedef TrackMarking_<ContainerAllocator> Type;

  TrackMarking_()
    : pose()
    , type(0)  {
    }
  TrackMarking_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TRACK_MARKING_TYPE_UNKNOWN)
  #undef TRACK_MARKING_TYPE_UNKNOWN
#endif
#if defined(_WIN32) && defined(TRACK_MARKING_TYPE_LEFT)
  #undef TRACK_MARKING_TYPE_LEFT
#endif
#if defined(_WIN32) && defined(TRACK_MARKING_TYPE_RIGHT)
  #undef TRACK_MARKING_TYPE_RIGHT
#endif
#if defined(_WIN32) && defined(TRACK_MARKING_TYPE_START_STOP)
  #undef TRACK_MARKING_TYPE_START_STOP
#endif

  enum {
    TRACK_MARKING_TYPE_UNKNOWN = 0u,
    TRACK_MARKING_TYPE_LEFT = 1u,
    TRACK_MARKING_TYPE_RIGHT = 2u,
    TRACK_MARKING_TYPE_START_STOP = 4u,
  };


  typedef boost::shared_ptr< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> const> ConstPtr;

}; // struct TrackMarking_

typedef ::tuw_vehicle_msgs::TrackMarking_<std::allocator<void> > TrackMarking;

typedef boost::shared_ptr< ::tuw_vehicle_msgs::TrackMarking > TrackMarkingPtr;
typedef boost::shared_ptr< ::tuw_vehicle_msgs::TrackMarking const> TrackMarkingConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator1> & lhs, const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator1> & lhs, const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuw_vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "648cedcb83e283b2403b91f87175eb19";
  }

  static const char* value(const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x648cedcb83e283b2ULL;
  static const uint64_t static_value2 = 0x403b91f87175eb19ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuw_vehicle_msgs/TrackMarking";
  }

  static const char* value(const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# single marking on the track\n"
"\n"
"# position of the marking in space, as well as normal angle along the racetrack path\n"
"geometry_msgs/Pose2D pose\n"
"\n"
"# type of track marking\n"
"uint8 type\n"
"\n"
"uint8 TRACK_MARKING_TYPE_UNKNOWN = 0\n"
"uint8 TRACK_MARKING_TYPE_LEFT = 1\n"
"uint8 TRACK_MARKING_TYPE_RIGHT = 2\n"
"uint8 TRACK_MARKING_TYPE_START_STOP = 4\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackMarking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuw_vehicle_msgs::TrackMarking_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUW_VEHICLE_MSGS_MESSAGE_TRACKMARKING_H
