(cl:defpackage tuw_object_msgs-msg
  (:use )
  (:export
   "<OBJECT>"
   "OBJECT"
   "<OBJECTDETECTION>"
   "OBJECTDETECTION"
   "<OBJECTSTAMPED>"
   "OBJECTSTAMPED"
   "<OBJECTWITHCOVARIANCE>"
   "OBJECTWITHCOVARIANCE"
   "<OBJECTWITHCOVARIANCEARRAY>"
   "OBJECTWITHCOVARIANCEARRAY"
   "<OBJECTWITHCOVARIANCEARRAYARRAY>"
   "OBJECTWITHCOVARIANCEARRAYARRAY"
   "<OBJECTWITHCOVARIANCESTAMPED>"
   "OBJECTWITHCOVARIANCESTAMPED"
  ))

