; Auto-generated. Do not edit!


(cl:in-package tuw_object_msgs-msg)


;//! \htmlinclude ObjectWithCovariance.msg.html

(cl:defclass <ObjectWithCovariance> (roslisp-msg-protocol:ros-message)
  ((object
    :reader object
    :initarg :object
    :type tuw_object_msgs-msg:Object
    :initform (cl:make-instance 'tuw_object_msgs-msg:Object))
   (covariance_pose
    :reader covariance_pose
    :initarg :covariance_pose
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (covariance_twist
    :reader covariance_twist
    :initarg :covariance_twist
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (correlation
    :reader correlation
    :initarg :correlation
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ObjectWithCovariance (<ObjectWithCovariance>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjectWithCovariance>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjectWithCovariance)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tuw_object_msgs-msg:<ObjectWithCovariance> is deprecated: use tuw_object_msgs-msg:ObjectWithCovariance instead.")))

(cl:ensure-generic-function 'object-val :lambda-list '(m))
(cl:defmethod object-val ((m <ObjectWithCovariance>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_object_msgs-msg:object-val is deprecated.  Use tuw_object_msgs-msg:object instead.")
  (object m))

(cl:ensure-generic-function 'covariance_pose-val :lambda-list '(m))
(cl:defmethod covariance_pose-val ((m <ObjectWithCovariance>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_object_msgs-msg:covariance_pose-val is deprecated.  Use tuw_object_msgs-msg:covariance_pose instead.")
  (covariance_pose m))

(cl:ensure-generic-function 'covariance_twist-val :lambda-list '(m))
(cl:defmethod covariance_twist-val ((m <ObjectWithCovariance>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_object_msgs-msg:covariance_twist-val is deprecated.  Use tuw_object_msgs-msg:covariance_twist instead.")
  (covariance_twist m))

(cl:ensure-generic-function 'correlation-val :lambda-list '(m))
(cl:defmethod correlation-val ((m <ObjectWithCovariance>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_object_msgs-msg:correlation-val is deprecated.  Use tuw_object_msgs-msg:correlation instead.")
  (correlation m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjectWithCovariance>) ostream)
  "Serializes a message object of type '<ObjectWithCovariance>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'covariance_pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'covariance_pose))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'covariance_twist))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'covariance_twist))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'correlation))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'correlation))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjectWithCovariance>) istream)
  "Deserializes a message object of type '<ObjectWithCovariance>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'covariance_pose) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'covariance_pose)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'covariance_twist) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'covariance_twist)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'correlation) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'correlation)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjectWithCovariance>)))
  "Returns string type for a message object of type '<ObjectWithCovariance>"
  "tuw_object_msgs/ObjectWithCovariance")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjectWithCovariance)))
  "Returns string type for a message object of type 'ObjectWithCovariance"
  "tuw_object_msgs/ObjectWithCovariance")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjectWithCovariance>)))
  "Returns md5sum for a message object of type '<ObjectWithCovariance>"
  "7f5bff1206fce53cd48a87798c13655f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjectWithCovariance)))
  "Returns md5sum for a message object of type 'ObjectWithCovariance"
  "7f5bff1206fce53cd48a87798c13655f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjectWithCovariance>)))
  "Returns full string definition for message of type '<ObjectWithCovariance>"
  (cl:format cl:nil "# This expresses a object in free space with uncertainty.~%~%Object object~%~%# Row-major representation of the 6x6 covariance matrix~%# The orientation parameters use a fixed-axis representation.~%# In order, the parameters are:~%# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)~%~%float64[] covariance_pose   # pose covariance if it exists it will be 3x3 or 6x6~%float64[] covariance_twist  # twist covariance if it exists it will be 3x3 or 6x6~%float64[] correlation       # correlation between pose and twist if it exists it will be 3x3 or 6x6~%================================================================================~%MSG: tuw_object_msgs/Object~%# This expresses a object in a 3D space~%int32[] ids                  # possible ids of the detected object (empty if no id could be identified/assigned)~%int32   shape                # shape type (possible types are listed below)~%float64[] shape_variables    # variables correspoding to the shape of the object (possible types are listed below)~%float64[] ids_confidence     # confidence of the possible ids in [0, 1]~%geometry_msgs/Pose pose      # pose of the detected object~%geometry_msgs/Twist twist    # twist of the detected object~%~%# SHAPE_TYPE                      # SHAPE_VARIABLES~%# ====================================================~%int32 SHAPE_UNKOWN           = 0  # []~%int32 SHAPE_POINT            = 1  # []~%int32 SHAPE_CIRCLE           = 2  # [radius]~%int32 SHAPE_ELLIPSE          = 3  # [radius1, radius2]~%int32 SHAPE_SQUARE           = 4  # [width]~%int32 SHAPE_RECTANGLE        = 5  # [length, width]~%int32 SHAPE_HULL             = 6  # [p0, p1, p2, ...]~%int32 SHAPE_LINE             = 7  # [] or [length] ~%~%int32 SHAPE_SPHERE           = 102~%int32 SHAPE_ELLIPSOID        = 103~%int32 SHAPE_CUBE             = 104~%int32 SHAPE_BOX              = 105~%int32 SHAPE_MESH             = 106~%~%int32 SHAPE_TRAFFIC_CONE     = 201 # [radius, color(1 = blue, 2 = yellow, 3 = red)] ~%int32 SHAPE_DOOR             = 202 # [width, height, opening angle (0=closed), nr of door leafs, clockwise (0) counterclockwise (1)]~%int32 SHAPE_MAP_DOOR         = 212 # for doors already mapped, same parameters as usual door~%int32 SHAPE_PERSON           = 203~%int32 SHAPE_VEHICLE          = 204~%int32 SHAPE_FIDUCIAL         = 205~%int32 SHAPE_CONE             = 206 # [radius, height]~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjectWithCovariance)))
  "Returns full string definition for message of type 'ObjectWithCovariance"
  (cl:format cl:nil "# This expresses a object in free space with uncertainty.~%~%Object object~%~%# Row-major representation of the 6x6 covariance matrix~%# The orientation parameters use a fixed-axis representation.~%# In order, the parameters are:~%# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)~%~%float64[] covariance_pose   # pose covariance if it exists it will be 3x3 or 6x6~%float64[] covariance_twist  # twist covariance if it exists it will be 3x3 or 6x6~%float64[] correlation       # correlation between pose and twist if it exists it will be 3x3 or 6x6~%================================================================================~%MSG: tuw_object_msgs/Object~%# This expresses a object in a 3D space~%int32[] ids                  # possible ids of the detected object (empty if no id could be identified/assigned)~%int32   shape                # shape type (possible types are listed below)~%float64[] shape_variables    # variables correspoding to the shape of the object (possible types are listed below)~%float64[] ids_confidence     # confidence of the possible ids in [0, 1]~%geometry_msgs/Pose pose      # pose of the detected object~%geometry_msgs/Twist twist    # twist of the detected object~%~%# SHAPE_TYPE                      # SHAPE_VARIABLES~%# ====================================================~%int32 SHAPE_UNKOWN           = 0  # []~%int32 SHAPE_POINT            = 1  # []~%int32 SHAPE_CIRCLE           = 2  # [radius]~%int32 SHAPE_ELLIPSE          = 3  # [radius1, radius2]~%int32 SHAPE_SQUARE           = 4  # [width]~%int32 SHAPE_RECTANGLE        = 5  # [length, width]~%int32 SHAPE_HULL             = 6  # [p0, p1, p2, ...]~%int32 SHAPE_LINE             = 7  # [] or [length] ~%~%int32 SHAPE_SPHERE           = 102~%int32 SHAPE_ELLIPSOID        = 103~%int32 SHAPE_CUBE             = 104~%int32 SHAPE_BOX              = 105~%int32 SHAPE_MESH             = 106~%~%int32 SHAPE_TRAFFIC_CONE     = 201 # [radius, color(1 = blue, 2 = yellow, 3 = red)] ~%int32 SHAPE_DOOR             = 202 # [width, height, opening angle (0=closed), nr of door leafs, clockwise (0) counterclockwise (1)]~%int32 SHAPE_MAP_DOOR         = 212 # for doors already mapped, same parameters as usual door~%int32 SHAPE_PERSON           = 203~%int32 SHAPE_VEHICLE          = 204~%int32 SHAPE_FIDUCIAL         = 205~%int32 SHAPE_CONE             = 206 # [radius, height]~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjectWithCovariance>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'covariance_pose) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'covariance_twist) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'correlation) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjectWithCovariance>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjectWithCovariance
    (cl:cons ':object (object msg))
    (cl:cons ':covariance_pose (covariance_pose msg))
    (cl:cons ':covariance_twist (covariance_twist msg))
    (cl:cons ':correlation (correlation msg))
))
