// Generated by gencpp from file tuw_geometry_msgs/WeightedPoseWithCovarianceArray.msg
// DO NOT EDIT!


#ifndef TUW_GEOMETRY_MSGS_MESSAGE_WEIGHTEDPOSEWITHCOVARIANCEARRAY_H
#define TUW_GEOMETRY_MSGS_MESSAGE_WEIGHTEDPOSEWITHCOVARIANCEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tuw_geometry_msgs/WeightedPoseWithCovariance.h>

namespace tuw_geometry_msgs
{
template <class ContainerAllocator>
struct WeightedPoseWithCovarianceArray_
{
  typedef WeightedPoseWithCovarianceArray_<ContainerAllocator> Type;

  WeightedPoseWithCovarianceArray_()
    : header()
    , poses()  {
    }
  WeightedPoseWithCovarianceArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tuw_geometry_msgs::WeightedPoseWithCovariance_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tuw_geometry_msgs::WeightedPoseWithCovariance_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> const> ConstPtr;

}; // struct WeightedPoseWithCovarianceArray_

typedef ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<std::allocator<void> > WeightedPoseWithCovarianceArray;

typedef boost::shared_ptr< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray > WeightedPoseWithCovarianceArrayPtr;
typedef boost::shared_ptr< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray const> WeightedPoseWithCovarianceArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator1> & lhs, const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator1> & lhs, const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuw_geometry_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f611e94fdb32f52eaee4a5137d1fa202";
  }

  static const char* value(const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf611e94fdb32f52eULL;
  static const uint64_t static_value2 = 0xaee4a5137d1fa202ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuw_geometry_msgs/WeightedPoseWithCovarianceArray";
  }

  static const char* value(const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"WeightedPoseWithCovariance[] poses\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tuw_geometry_msgs/WeightedPoseWithCovariance\n"
"# This represents a pose in free space with uncertainty and a scoring weight.\n"
"\n"
"geometry_msgs/Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"# [0, 1] weight of the pose, used for scoring a pose particle\n"
"float64 weight\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeightedPoseWithCovarianceArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuw_geometry_msgs::WeightedPoseWithCovarianceArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tuw_geometry_msgs::WeightedPoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUW_GEOMETRY_MSGS_MESSAGE_WEIGHTEDPOSEWITHCOVARIANCEARRAY_H
