; Auto-generated. Do not edit!


(cl:in-package tuw_local_controller_msgs-msg)


;//! \htmlinclude ExecutePathFeedback.msg.html

(cl:defclass <ExecutePathFeedback> (roslisp-msg-protocol:ros-message)
  ((current_step
    :reader current_step
    :initarg :current_step
    :type cl:integer
    :initform 0))
)

(cl:defclass ExecutePathFeedback (<ExecutePathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutePathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutePathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tuw_local_controller_msgs-msg:<ExecutePathFeedback> is deprecated: use tuw_local_controller_msgs-msg:ExecutePathFeedback instead.")))

(cl:ensure-generic-function 'current_step-val :lambda-list '(m))
(cl:defmethod current_step-val ((m <ExecutePathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_local_controller_msgs-msg:current_step-val is deprecated.  Use tuw_local_controller_msgs-msg:current_step instead.")
  (current_step m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutePathFeedback>) ostream)
  "Serializes a message object of type '<ExecutePathFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_step)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutePathFeedback>) istream)
  "Deserializes a message object of type '<ExecutePathFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_step) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutePathFeedback>)))
  "Returns string type for a message object of type '<ExecutePathFeedback>"
  "tuw_local_controller_msgs/ExecutePathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutePathFeedback)))
  "Returns string type for a message object of type 'ExecutePathFeedback"
  "tuw_local_controller_msgs/ExecutePathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutePathFeedback>)))
  "Returns md5sum for a message object of type '<ExecutePathFeedback>"
  "f693c0c693fe0398ee7588f0a3c6259d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutePathFeedback)))
  "Returns md5sum for a message object of type 'ExecutePathFeedback"
  "f693c0c693fe0398ee7588f0a3c6259d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutePathFeedback>)))
  "Returns full string definition for message of type '<ExecutePathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 current_step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutePathFeedback)))
  "Returns full string definition for message of type 'ExecutePathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 current_step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutePathFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutePathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutePathFeedback
    (cl:cons ':current_step (current_step msg))
))
