// Generated by gencpp from file tuw_multi_robot_msgs/StationManagerControlProtocol.msg
// DO NOT EDIT!


#ifndef TUW_MULTI_ROBOT_MSGS_MESSAGE_STATIONMANAGERCONTROLPROTOCOL_H
#define TUW_MULTI_ROBOT_MSGS_MESSAGE_STATIONMANAGERCONTROLPROTOCOL_H

#include <ros/service_traits.h>


#include <tuw_multi_robot_msgs/StationManagerControlProtocolRequest.h>
#include <tuw_multi_robot_msgs/StationManagerControlProtocolResponse.h>


namespace tuw_multi_robot_msgs
{

struct StationManagerControlProtocol
{

typedef StationManagerControlProtocolRequest Request;
typedef StationManagerControlProtocolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StationManagerControlProtocol
} // namespace tuw_multi_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocol > {
  static const char* value()
  {
    return "4c3ba04d64c7726241cb44a482e7d069";
  }

  static const char* value(const ::tuw_multi_robot_msgs::StationManagerControlProtocol&) { return value(); }
};

template<>
struct DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocol > {
  static const char* value()
  {
    return "tuw_multi_robot_msgs/StationManagerControlProtocol";
  }

  static const char* value(const ::tuw_multi_robot_msgs::StationManagerControlProtocol&) { return value(); }
};


// service_traits::MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocolRequest> should match
// service_traits::MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocol >
template<>
struct MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocol >::value();
  }
  static const char* value(const ::tuw_multi_robot_msgs::StationManagerControlProtocolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocolRequest> should match
// service_traits::DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocol >
template<>
struct DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocolRequest>
{
  static const char* value()
  {
    return DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocol >::value();
  }
  static const char* value(const ::tuw_multi_robot_msgs::StationManagerControlProtocolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocolResponse> should match
// service_traits::MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocol >
template<>
struct MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tuw_multi_robot_msgs::StationManagerControlProtocol >::value();
  }
  static const char* value(const ::tuw_multi_robot_msgs::StationManagerControlProtocolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocolResponse> should match
// service_traits::DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocol >
template<>
struct DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocolResponse>
{
  static const char* value()
  {
    return DataType< ::tuw_multi_robot_msgs::StationManagerControlProtocol >::value();
  }
  static const char* value(const ::tuw_multi_robot_msgs::StationManagerControlProtocolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUW_MULTI_ROBOT_MSGS_MESSAGE_STATIONMANAGERCONTROLPROTOCOL_H
