(cl:defpackage tuw_multi_robot_msgs-srv
  (:use )
  (:export
   "STATIONMANAGERCONTROLPROTOCOL"
   "<STATIONMANAGERCONTROLPROTOCOL-REQUEST>"
   "STATIONMANAGERCONTROLPROTOCOL-REQUEST"
   "<STATIONMANAGERCONTROLPROTOCOL-RESPONSE>"
   "STATIONMANAGERCONTROLPROTOCOL-RESPONSE"
   "STATIONMANAGERSTATIONPROTOCOL"
   "<STATIONMANAGERSTATIONPROTOCOL-REQUEST>"
   "STATIONMANAGERSTATIONPROTOCOL-REQUEST"
   "<STATIONMANAGERSTATIONPROTOCOL-RESPONSE>"
   "STATIONMANAGERSTATIONPROTOCOL-RESPONSE"
  ))

