//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the tuw_multi_robot_router package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __tuw_multi_robot_router__ROUTERCONFIG_H__
#define __tuw_multi_robot_router__ROUTERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace tuw_multi_robot_router
{
  class routerConfigStatics;

  class routerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(routerConfig &config, const routerConfig &max, const routerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const routerConfig &config1, const routerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, routerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const routerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, routerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const routerConfig &config) const = 0;
      virtual void getValue(const routerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T routerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T routerConfig::* field;

      virtual void clamp(routerConfig &config, const routerConfig &max, const routerConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const routerConfig &config1, const routerConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, routerConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const routerConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, routerConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const routerConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const routerConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, routerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, routerConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<routerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(routerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("publish_routing_table"==(*_i)->name){publish_routing_table = boost::any_cast<bool>(val);}
        if("voronoi_graph"==(*_i)->name){voronoi_graph = boost::any_cast<bool>(val);}
        if("priority_rescheduling"==(*_i)->name){priority_rescheduling = boost::any_cast<bool>(val);}
        if("speed_rescheduling"==(*_i)->name){speed_rescheduling = boost::any_cast<bool>(val);}
        if("router_time_limit_s"==(*_i)->name){router_time_limit_s = boost::any_cast<double>(val);}
        if("topic_timeout_s"==(*_i)->name){topic_timeout_s = boost::any_cast<double>(val);}
        if("path_endpoint_optimization"==(*_i)->name){path_endpoint_optimization = boost::any_cast<bool>(val);}
        if("collision_resolver"==(*_i)->name){collision_resolver = boost::any_cast<int>(val);}
        if("goal_mode"==(*_i)->name){goal_mode = boost::any_cast<int>(val);}
        if("router_type"==(*_i)->name){router_type = boost::any_cast<int>(val);}
        if("nr_threads"==(*_i)->name){nr_threads = boost::any_cast<int>(val);}
      }
    }

    bool publish_routing_table;
bool voronoi_graph;
bool priority_rescheduling;
bool speed_rescheduling;
double router_time_limit_s;
double topic_timeout_s;
bool path_endpoint_optimization;
int collision_resolver;
int goal_mode;
int router_type;
int nr_threads;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool publish_routing_table;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool voronoi_graph;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool priority_rescheduling;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool speed_rescheduling;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double router_time_limit_s;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double topic_timeout_s;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool path_endpoint_optimization;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int collision_resolver;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int goal_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int router_type;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int nr_threads;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("routerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const routerConfig &__max__ = __getMax__();
      const routerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const routerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const routerConfig &__getDefault__();
    static const routerConfig &__getMax__();
    static const routerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const routerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void routerConfig::ParamDescription<std::string>::clamp(routerConfig &config, const routerConfig &max, const routerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class routerConfigStatics
  {
    friend class routerConfig;

    routerConfigStatics()
    {
routerConfig::GroupDescription<routerConfig::DEFAULT, routerConfig> Default("Default", "", 0, 0, true, &routerConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publish_routing_table = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publish_routing_table = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publish_routing_table = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("publish_routing_table", "bool", 0, "On false it won't publish the routing table even a valid route was found", "", &routerConfig::publish_routing_table)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("publish_routing_table", "bool", 0, "On false it won't publish the routing table even a valid route was found", "", &routerConfig::publish_routing_table)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.voronoi_graph = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.voronoi_graph = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.voronoi_graph = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("voronoi_graph", "bool", 0, "Defines if the generated Graph is a voronoi one (in doubt use false)", "", &routerConfig::voronoi_graph)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("voronoi_graph", "bool", 0, "Defines if the generated Graph is a voronoi one (in doubt use false)", "", &routerConfig::voronoi_graph)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.priority_rescheduling = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.priority_rescheduling = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.priority_rescheduling = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("priority_rescheduling", "bool", 0, "Defines if priority rescheduling is used", "", &routerConfig::priority_rescheduling)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("priority_rescheduling", "bool", 0, "Defines if priority rescheduling is used", "", &routerConfig::priority_rescheduling)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.speed_rescheduling = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.speed_rescheduling = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.speed_rescheduling = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("speed_rescheduling", "bool", 0, "Defines if speed rescheduling is used", "", &routerConfig::speed_rescheduling)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("speed_rescheduling", "bool", 0, "Defines if speed rescheduling is used", "", &routerConfig::speed_rescheduling)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.router_time_limit_s = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.router_time_limit_s = 300.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.router_time_limit_s = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<double>("router_time_limit_s", "double", 0, "Sets the upper limit for a planning approach. (router time is not overall time)", "", &routerConfig::router_time_limit_s)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<double>("router_time_limit_s", "double", 0, "Sets the upper limit for a planning approach. (router time is not overall time)", "", &routerConfig::router_time_limit_s)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.topic_timeout_s = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.topic_timeout_s = 300.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.topic_timeout_s = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<double>("topic_timeout_s", "double", 0, "Sets the timeout for deleting latched topics", "", &routerConfig::topic_timeout_s)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<double>("topic_timeout_s", "double", 0, "Sets the timeout for deleting latched topics", "", &routerConfig::topic_timeout_s)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_endpoint_optimization = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_endpoint_optimization = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_endpoint_optimization = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("path_endpoint_optimization", "bool", 0, "optimizes the path (only possible for 1 robot)", "", &routerConfig::path_endpoint_optimization)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<bool>("path_endpoint_optimization", "bool", 0, "optimizes the path (only possible for 1 robot)", "", &routerConfig::path_endpoint_optimization)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.collision_resolver = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.collision_resolver = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.collision_resolver = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("collision_resolver", "int", 0, "The used collision resolver for the multi robot planner", "{'enum': [{'name': 'None', 'type': 'int', 'value': 0, 'srcline': 15, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'No collision Resolver (Standard A-Star)', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Backtracking', 'type': 'int', 'value': 1, 'srcline': 16, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'Backtracking (includes wait steps)', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Avoidance', 'type': 'int', 'value': 2, 'srcline': 17, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'Avoidance (includes wait steps and can avoid other robots in crossings)', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Collision resolver type'}", &routerConfig::collision_resolver)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("collision_resolver", "int", 0, "The used collision resolver for the multi robot planner", "{'enum': [{'name': 'None', 'type': 'int', 'value': 0, 'srcline': 15, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'No collision Resolver (Standard A-Star)', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Backtracking', 'type': 'int', 'value': 1, 'srcline': 16, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'Backtracking (includes wait steps)', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Avoidance', 'type': 'int', 'value': 2, 'srcline': 17, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'Avoidance (includes wait steps and can avoid other robots in crossings)', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Collision resolver type'}", &routerConfig::collision_resolver)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_mode = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_mode = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("goal_mode", "int", 0, "The endpoint mode", "{'enum': [{'name': 'use_map_goal', 'type': 'int', 'value': 0, 'srcline': 22, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'endpoint is maped to the real endpoint', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'use_voronoi_goal', 'type': 'int', 'value': 1, 'srcline': 23, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'endpoint is mapped to the end point on the segment', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'use_segment_goal', 'type': 'int', 'value': 2, 'srcline': 24, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'endpoint is mapped to the corresponding segment endpoint', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Collision resolver type'}", &routerConfig::goal_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("goal_mode", "int", 0, "The endpoint mode", "{'enum': [{'name': 'use_map_goal', 'type': 'int', 'value': 0, 'srcline': 22, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'endpoint is maped to the real endpoint', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'use_voronoi_goal', 'type': 'int', 'value': 1, 'srcline': 23, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'endpoint is mapped to the end point on the segment', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'use_segment_goal', 'type': 'int', 'value': 2, 'srcline': 24, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'endpoint is mapped to the corresponding segment endpoint', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Collision resolver type'}", &routerConfig::goal_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.router_type = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.router_type = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.router_type = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("router_type", "int", 0, "Router Type", "{'enum': [{'name': 'standard_rotuer', 'type': 'int', 'value': 0, 'srcline': 29, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'standard single threaded router', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'threaded_rotuer_srr', 'type': 'int', 'value': 1, 'srcline': 30, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'multithreaded robot router', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Multi_robot_router_type'}", &routerConfig::router_type)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("router_type", "int", 0, "Router Type", "{'enum': [{'name': 'standard_rotuer', 'type': 'int', 'value': 0, 'srcline': 29, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'standard single threaded router', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'threaded_rotuer_srr', 'type': 'int', 'value': 1, 'srcline': 30, 'srcfile': '/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg', 'description': 'multithreaded robot router', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Multi_robot_router_type'}", &routerConfig::router_type)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.nr_threads = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.nr_threads = 64;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.nr_threads = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("nr_threads", "int", 0, "sets the number of threads for the selected router", "", &routerConfig::nr_threads)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(routerConfig::AbstractParamDescriptionConstPtr(new routerConfig::ParamDescription<int>("nr_threads", "int", 0, "sets the number of threads for the selected router", "", &routerConfig::nr_threads)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(routerConfig::AbstractGroupDescriptionConstPtr(new routerConfig::GroupDescription<routerConfig::DEFAULT, routerConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<routerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<routerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<routerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    routerConfig __max__;
    routerConfig __min__;
    routerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const routerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static routerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &routerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const routerConfig &routerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const routerConfig &routerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const routerConfig &routerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<routerConfig::AbstractParamDescriptionConstPtr> &routerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<routerConfig::AbstractGroupDescriptionConstPtr> &routerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const routerConfigStatics *routerConfig::__get_statics__()
  {
    const static routerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = routerConfigStatics::get_instance();

    return statics;
  }

//#line 15 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_None = 0;
//#line 16 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_Backtracking = 1;
//#line 17 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_Avoidance = 2;
//#line 22 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_use_map_goal = 0;
//#line 23 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_use_voronoi_goal = 1;
//#line 24 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_use_segment_goal = 2;
//#line 29 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_standard_rotuer = 0;
//#line 30 "/home/alvina/new_proj/src/tuv/tuw_multi_robot/tuw_multi_robot_router/cfg/router.cfg"
      const int router_threaded_rotuer_srr = 1;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ROUTERRECONFIGURATOR_H__
