// Generated by gencpp from file tuw_airskin_msgs/AirskinInfo.msg
// DO NOT EDIT!


#ifndef TUW_AIRSKIN_MSGS_MESSAGE_AIRSKININFO_H
#define TUW_AIRSKIN_MSGS_MESSAGE_AIRSKININFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tuw_airskin_msgs
{
template <class ContainerAllocator>
struct AirskinInfo_
{
  typedef AirskinInfo_<ContainerAllocator> Type;

  AirskinInfo_()
    : header()
    , ids()
    , names()
    , min()
    , max()  {
    }
  AirskinInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ids(_alloc)
    , names(_alloc)
    , min(_alloc)
    , max(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _ids_type;
  _ids_type ids;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _min_type;
  _min_type min;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> const> ConstPtr;

}; // struct AirskinInfo_

typedef ::tuw_airskin_msgs::AirskinInfo_<std::allocator<void> > AirskinInfo;

typedef boost::shared_ptr< ::tuw_airskin_msgs::AirskinInfo > AirskinInfoPtr;
typedef boost::shared_ptr< ::tuw_airskin_msgs::AirskinInfo const> AirskinInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator1> & lhs, const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ids == rhs.ids &&
    lhs.names == rhs.names &&
    lhs.min == rhs.min &&
    lhs.max == rhs.max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator1> & lhs, const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuw_airskin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14394f7dbdb0d73a010ea995f889c657";
  }

  static const char* value(const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14394f7dbdb0d73aULL;
  static const uint64_t static_value2 = 0x010ea995f889c657ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuw_airskin_msgs/AirskinInfo";
  }

  static const char* value(const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This expresses a set of AirSkin pad pressures\n"
"Header header                  # timestamp in the header is the acquisition time and frame\n"
"\n"
"uint8[] ids                    # I2C ids of target AirSkin pads\n"
"string[] names                 # names and TF frames names of corresponding AirSkin pads\n"
"uint32[] min                   # pressure min value\n"
"uint32[] max                   # pressure max value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ids);
      stream.next(m.names);
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AirskinInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuw_airskin_msgs::AirskinInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "min[]" << std::endl;
    for (size_t i = 0; i < v.min.size(); ++i)
    {
      s << indent << "  min[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.min[i]);
    }
    s << indent << "max[]" << std::endl;
    for (size_t i = 0; i < v.max.size(); ++i)
    {
      s << indent << "  max[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.max[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUW_AIRSKIN_MSGS_MESSAGE_AIRSKININFO_H
